apiVersion: v1
kind: Service
metadata:
  name: svc-ssh-{{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    app: {{ .Values.name }}
